{{- if not .Values.apiKeySecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxera-agent.fullname" . }}-api-key
  labels:
    app.kubernetes.io/name: {{ include "proxera-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  PROXERA_API_KEY: {{ required "Either apiKey or apiKeySecret.name must be set" .Values.apiKey | b64enc | quote }}
{{- end }}
